---
title: "Terms and conditions for users of herbarium.biodiversity.cz (HERBIO)"
---

1. Only data directly generated by digitalization of herbarium specimens are allowed to be deposited in the HERBIO. Any data that does not fall within this category will be removed without warning and will result in a permanent ban of the user from making further deposition in the HERBIO. In the case of illegal material, the relevant authorities will be notified.

2. A record is defined as the set of deposited image file and deposited metadata. Although the record can be in various states, this does not change the which rules apply to them, with the exception that the License is not applied until the record is published.

3. Depositors agrees that HERBIO can distribute the users' records under the [CC-BY 4.0 Attribution](https://creativecommons.org/licenses/by/4.0/), i.e., the user agrees to place their work in the public domain.

4. Every person involved with the record is responsible for the record being correct (defined is not-fraudulent and containing non-allowed data), this extent to the HERBIO members. The principal contact and depositor as well as HERBIO members are obliged to keep their contact information updated in case doubt arises. Failure of correctness or contact information can in worst case lead to deletion of the record and permanent banning from making depositions. In the case of HERBIO members termination of any rights they may have within the HERBIO and permanent banning from participating in any form.

5. Every person involved in generation and deposition of the data must agree on being associated with the record and agree that the data can be placed in the public domain.

6. Users have the right to request deletion of their record. However, as the data is in the public domain, this in practice only means that HERBIO will seize to distribute the data. HERBIO has no rights too interfere with data downloaded prior to deletion, including redistribution. Furthermore, minimal metadata cannot be deleted. A note that the user requested deletion of the record will be present on the record landing page.

7. Users are only allowed to deposit work they have been directly involved with the herbarium they are delegated to work on.

8. Sanctions for fraudulent behaviour include:
    1. Forced alteration of record.
    2. Deletion of record with the note that it was deleted due to fraudulence.
    3. Permanent banning of one or all of the depositors from depositing within the HERBIO.
    4. HERBIO will attempt to notify all users of the data of it’s fraudulence, including Journal publishers.
    5. HERBIO will notify the relevant legal authorities, including the employers of one or all of the depositors.

9. HERBIO are allowed to change the records by following the procedures  set out by the steering committee.