name: Build Quarto site

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            ggplot2
            httr2
            jsonlite
            rmarkdown

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

